### ISSUE TITLE
(Fedora ) Cache location (in order to move it to RAM)

### ISSUE THREAD

**Issue by Shogu** [flathub/com.opera.Opera#81]
Hi and thanks for this browser, i used it with pleasure since many years after having tried dozens of others!

On my linux systems, i am used to move the cache folder of my browsers directly into RAM in order to gain some speed.

It is easy with a "standard" opera installation via *.rpm or *.deb package, using the "--disk-cache-dir=" command on the opera shortcut, but now i am using Flatpak to install Opera :  is there any way to command Opera to use a personnal path for its cache?

Adding the --disk-cache command on the flatpak opera shortcut do not works, un fortunately

Thans a lot in advance

Greetings from France

Ogu

**Comment by Gaeldrin** [comment]
Hello Ogu,

first of all, welcome and thank you for your kind words, I appreciate it! :)

Now to your question. I've never done something like that but here are my two cents.

The parameter `--disk-cache-dir=` (or any other parameter) should work normally, Flatpak just passes it to Opera. Just like you mentioned in the other issue for changing the language (thanks for that btw! :+1: ). However, it is important to keep in mind that Flatpak is sandboxing the app. I believe that the command changes the location of the cache folder **inside the sandbox**, not on your host system. Because of the very same sandboxing, giving the Opera flatpak access to the whole filesystem is not my first choice for public release.

That being said, I think there are multiple ways for you to accomplish what you want (that is the beauty of Linux after all). 

1. My first idea after some research is for you to give the Opera flatpak access to a specific path on your system, for example [this article](https://devicetests.com/flatpak-app-external-directories) or [this forum post](https://askubuntu.com/questions/1086529/how-to-give-a-flatpak-app-access-to-a-directory). Together with the parameter you mentioned, I think it could work, depends on how you access your RAM.
2. Alternatively, I think you could trick Flatpak and point it's home directory to the Ram(disk?) with a symlink and have the whole Opera config in RAM. A little bit crazy idea, I know. :D

In any case, please share if you were successful, and have a nice day!

Cheers,
Petr
