### ISSUE TITLE
Save as dialog is sandboxed, this creates a massive problem storing documents and images

### ISSUE THREAD

**Issue by nmondal** [flathub/com.opera.Opera#82]
They are not automatically picking up last image / document store location.

**Comment by Gaeldrin** [comment]
That is true but that is (as far as I can tell) how Flatpak behaves. I have installed Brave flatpak and it behaves exactly the same way (except it has an extra permission for the Desktop folder). I checked the code for Chrome and Vivaldi and I think they are the same too. Inside the Download folder, it remembers the selected subfolders. Outside it, generally you don't want your browser to have access to every file on your computer.

From what I can tell, the best way for you to allow directly storing files in a location outside your Download folder is to add the permission to the app on your computer (command line, Flatseal, etc.) if you need it regularly. I personally am sad that the Flatpak portal for downloading files does not behave the same way as the dialog for uploading, but I have no idea if that is problem of Flatpak, GTK, Chromium (since all chromium based flatpak browsers seem to have it), some obscure setting that I missed or something else.
